name: Build and test

on: [push, pull_request, workflow_dispatch]

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt -qqy update
          sudo apt -qqy install curl gnupg git cmake wget python3-dev python3-pip python3-setuptools python3-tk python3-wheel ninja-build
          pip3 install --upgrade pip
          pip3 install west
          mkdir -p zephyr-sdk && cd zephyr-sdk
          wget --progress=dot:giga  https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.13.2/zephyr-sdk-0.13.2-linux-x86_64-setup.run
          sh "zephyr-sdk-0.13.2-linux-x86_64-setup.run" --quiet -- -d /opt/toolchains/zephyr-sdk -y -norc

      - name: Download Zephyr
        run: |
          mkdir -p zephyrproject
          cd zephyrproject
          west init -m https://github.com/zephyrproject-rtos/zephyr --mr v2.7.0
          west update
          pip3 install -r zephyr/scripts/requirements.txt

      - name: Build sample
        run: |
          export ZEPHYR_BASE=$PWD/zephyrproject/zephyr
          source $ZEPHYR_BASE/zephyr-env.sh
          ./build_as.sh -b

      - name: Test in Renode
        uses: antmicro/renode-test-action@v3.0.0
        with:
          renode-version: '1.13.2'
          tests-to-run: 'tests/test_dijkstra_path_finding.robot'

      - uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            log.html
            report.html
            robot_output.xml


